### ISSUE TITLE
Turn off debug

### ISSUE THREAD

**Issue by SathiyalingamSenthilkumar** [LumenRadio/mira-large-packets#2]
The debug level is set to 2 in some of the source files. Is this intentional? If not I can make a PR with debugging turned off.

**Comment by fleutot** [comment]
This project is an implementation suggestion for users wanting to send large packets with Mira. It is not production ready. I am not aware of how much debug output comes through, I suppose that what is left might be useful for the user to understand in what order stuff is happening.

Is there any plan to use this as something else than an example? Again, the intent was to show how one could think about dealing with larger packets, not to be copied into production code.

**Comment by SathiyalingamSenthilkumar** [comment]
Yes, we are integrating this example into offnet-firmware. We have added this repo as a submodule and use the files in common directory.

**Comment by fleutot** [comment]
I see! I would suggest making a central control of debug levels, which you would set at application level (and let defaults for this stand-alone repo behave the same as today). I am biased towards an application level debug.h, that does something like this:

```
#define P_LEVEL_LARGE_PACKET  2
#if P_LEVEL_LARGE_PACKET >= 1
#define P_ERROR_LP(...) printf(__VA_ARGS__)
#else
#define P_ERROR_LP(...)
#endif

#if P_LEVEL_LARGE_PACKET >= 2
#define P_DEBUG_LP(...) printf(__VA_ARGS__)
#else
#define P_DEBUG_LP(...)
#endif
```

Or if you have a better idea to set debug levels of separate modules, at application level, let me know.

**Comment by SathiyalingamSenthilkumar** [comment]
Yeah, I will fix it in our application then. Thanks.

**Comment by fleutot** [comment]
You'll still need to change the calls in this repo, but I guess that will come later.
